(function(){
  "use strict";
  const A=window.MyMusicAnalytics,$=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
  let raw=A.createData(),data=null,agg=null,period="7d",rankingMetric="plays",imports=[];
  const esc=s=>String(s??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const int=n=>new Intl.NumberFormat("ja-JP").format(n||0),time=s=>s>=3600?`${(s/3600).toFixed(1)}時間`:`${Math.round((s||0)/60)}分`,pct=n=>n==null?"—":`${Math.round(n*100)}%`;
  const empty=message=>`<div class="empty-panel"><p>${message}</p><button class="open-import">JSONを読み込む</button></div>`;
  const metric=(label,value)=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;
  function table(headers,rows){if(!rows.length)return '<p class="empty">該当するデータがありません。</p>';return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th class="${h.num?'num':''}">${h.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td class="${h.num?'num':''}">${h.render?h.render(r[h.key],r):esc(r[h.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function bars(rows){const max=Math.max(1,...rows.map(r=>r.value));return rows.length?`<div class="bar-list">${rows.map(r=>`<div class="bar-row"><small title="${esc(r.label)}">${esc(r.label)}</small><div class="bar"><i style="width:${r.value/max*100}%"></i></div><strong>${int(r.value)}</strong></div>`).join('')}</div>`:'<p class="empty">データがありません。</p>'}
  function ranks(rows,formatter=int){return rows.length?rows.map((r,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div><strong>${esc(r.label)}</strong><small>${esc(r.sub||'')}</small></div><span>${formatter(r.value)}</span></div>`).join(''):'<p class="empty">データがありません。</p>'}
  function group(events,key,labelKey=key){const map=new Map();events.forEach(e=>{const label=e[labelKey]||"不明";const row=map.get(label)||{label,value:0,duration:0};row.value++;row.duration+=e.playDuration||0;map.set(label,row)});return [...map.values()]}
  function topTracks(events){const map=new Map();events.forEach(e=>{const t=data.trackMap.get(e.trackId)||e,row=map.get(e.trackId)||{label:t.title||e.trackTitle||e.trackId,sub:t.artist||e.artist,value:0,duration:0};row.value++;row.duration+=e.playDuration||0;map.set(e.trackId,row)});return [...map.values()]}
  function periodDates(){const today=new Date(),end=today.toISOString().slice(0,10);if(period==="all")return{};if(period==="custom")return{start:$("startDate").value,end:$("endDate").value};const days=period==="today"?1:period==="30d"?30:7,start=new Date(today);start.setDate(start.getDate()-days+1);return{start:start.toISOString().slice(0,10),end}}
  function render(){if(!data)return;const dates=periodDates();if(dates.start&&dates.end&&dates.start>dates.end){$("filterError").textContent="開始日は終了日以前にしてください。";return}$("filterError").textContent="";agg=A.aggregate(data,dates.start,dates.end);renderDashboard();renderHistory();renderInsights();renderRankings();renderTracks();renderSources();renderImport();bindImportButtons()}
  function renderDashboard(){const top=topTracks(agg.events).sort((a,b)=>b.value-a.value).slice(0,10),artists=group(agg.events,"artist").sort((a,b)=>b.value-a.value).slice(0,10),skips=topTracks(agg.events.filter(e=>e.skipped)).sort((a,b)=>b.value-a.value).slice(0,10),early=topTracks(agg.events.filter(e=>e.skipped&&e.playDuration<=30&&e.playedAt>=new Date("2026-08-31T15:00:00Z"))).sort((a,b)=>b.value-a.value).slice(0,10);$("dashboardView").innerHTML=`<div class="metrics">${metric("再生回数",int(agg.total.playCount))}${metric("再生時間",time(agg.total.playTime))}${metric("完走率",pct(agg.total.completionRate))}${metric("Skip率",pct(agg.total.skipRate))}${metric("Early Skip",int(agg.total.early))}</div><div class="grid two"><article class="panel"><h2>よく聴く曲</h2>${bars(top)}</article><article class="panel"><h2>Artist別再生数</h2>${bars(artists)}</article></div><div class="grid three"><article class="panel"><h2>Skipが多い曲</h2>${ranks(skips)}</article><article class="panel"><h2>Early Skipが多い曲</h2>${ranks(early)}</article><article class="panel"><h2>Good / Bad分布</h2>${ranks([{label:"Good",value:agg.tracks.filter(t=>t.preference?.playbackPreference>0).length},{label:"Neutral",value:agg.tracks.filter(t=>!t.preference?.playbackPreference).length},{label:"Bad",value:agg.tracks.filter(t=>t.preference?.playbackPreference<0).length}])}</article></div>`}
  function renderHistory(){if(!data.playEvents.length){$("historyView").innerHTML=empty("Playback Eventsを読み込むと月ごとの音楽史を表示します。");return}const months=new Map();data.playEvents.forEach(e=>{const key=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit"}).format(e.playedAt),m=months.get(key)||{events:[],artists:new Map()};m.events.push(e);m.artists.set(e.artist,(m.artists.get(e.artist)||0)+1);months.set(key,m)});$("historyView").innerHTML=`<div class="history-timeline">${[...months].sort((a,b)=>b[0].localeCompare(a[0])).map(([month,m])=>{const top=topTracks(m.events).sort((a,b)=>b.value-a.value)[0],artist=[...m.artists].sort((a,b)=>b[1]-a[1])[0];return `<article class="panel history-card"><p class="eyebrow">${esc(month)}</p><h2>${int(m.events.length)}回の再生</h2><p>${esc(top?.label||"—")} <span class="muted">／ ${esc(artist?.[0]||"—")}</span></p></article>`}).join('')}</div>`}
  function renderInsights(){if(!agg.events.length){$("insightsView").innerHTML=empty("再生データを読み込むとインサイトを表示します。");return}const sources=group(agg.events,"playSource").sort((a,b)=>b.value-a.value),selections=group(agg.events,"selectionType").sort((a,b)=>b.value-a.value),good=agg.tracks.filter(t=>t.playCount&&t.preference?.playbackPreference>0).sort((a,b)=>(b.completionRate||0)-(a.completionRate||0)).slice(0,10),risky=agg.tracks.filter(t=>t.early).sort((a,b)=>b.early-a.early).slice(0,10);$("insightsView").innerHTML=`<div class="grid three"><article class="panel"><p class="eyebrow">RECOMMENDATIONS</p><h2>好みと完走が一致</h2>${ranks(good.map(t=>({label:t.title,sub:t.artist,value:t.playCount})))}</article><article class="panel"><p class="eyebrow">EARLY SKIP</p><h2>見直したい曲</h2>${ranks(risky.map(t=>({label:t.title,sub:t.artist,value:t.early})))}</article><article class="panel"><p class="eyebrow">LISTENING PROFILE</p><h2>現在の聴き方</h2><div class="metrics">${metric("詳細再生",int(agg.total.detailCount))}${metric("完走",pct(agg.total.completionRate))}</div></article></div><div class="grid two"><article class="panel"><h2>再生入口</h2>${bars(sources.slice(0,12))}</article><article class="panel"><h2>選択種別</h2>${bars(selections.slice(0,12))}</article></div>`}
  function renderRankings(){if(!agg.events.length){$("rankingsView").innerHTML=empty("再生データを読み込むとランキングを表示します。");return}const value=r=>rankingMetric==="duration"?r.duration:r.value,formatter=rankingMetric==="duration"?time:int,sort=(a,b)=>value(b)-value(a),tracks=topTracks(agg.events).map(r=>({...r,value:value(r)})).sort(sort).slice(0,50),artists=group(agg.events,"artist").map(r=>({...r,value:value(r)})).sort(sort).slice(0,50),albums=group(agg.events,"album").map(r=>({...r,value:value(r)})).sort(sort).slice(0,50),genres=group(agg.events,"genre").map(r=>({...r,value:value(r)})).sort(sort).slice(0,50);$("rankingsView").innerHTML=`<div class="ranking-columns"><article class="panel"><h2>曲</h2>${ranks(tracks,formatter)}</article><article class="panel"><h2>Artist</h2>${ranks(artists,formatter)}</article><article class="panel"><h2>Album</h2>${ranks(albums,formatter)}</article><article class="panel"><h2>Genre</h2>${ranks(genres,formatter)}</article></div>`}
  function renderTracks(){if(!data.tracks.length){$("tracksView").innerHTML=empty("Library JSONを読み込むと曲ごとの傾向を表示します。");return}const q=$("trackSearch").value.trim().toLocaleLowerCase("ja"),rows=agg.tracks.filter(t=>!q||[t.title,t.artist,t.album,t.genre].some(v=>String(v||"").toLocaleLowerCase("ja").includes(q))).sort((a,b)=>b.playCount-a.playCount||String(a.title).localeCompare(String(b.title),"ja"));$("tracksView").innerHTML=`<article class="panel">${table([{key:"title",label:"曲"},{key:"artist",label:"Artist"},{key:"album",label:"Album"},{key:"favorite",label:"お気に入り",render:(_,r)=>r.preference?.favorite?'<span class="favorite">★</span>':'—'},{key:"preference",label:"Good / Bad",render:(_,r)=>r.preference?.playbackPreference??"—"},{key:"playCount",label:"再生",num:1,render:int},{key:"playTime",label:"再生時間",num:1,render:time},{key:"completionRate",label:"完走率",num:1,render:pct},{key:"skipRate",label:"Skip率",num:1,render:pct},{key:"early",label:"Early Skip",num:1,render:int}],rows)}</article>`}
  function renderSources(){if(!raw.sources.length){$("sourcesView").innerHTML=empty("JSONを読み込むとデータソースを一覧表示します。");return}const names={tracks:"Library",playEvents:"Playback Events",preferences:"Playback Preferences",features:"Track Features",volume:"Volume Normalization",playlists:"Playlists",equalizer:"Equalizer",genrePresets:"Genre Presets"};$("sourcesView").innerHTML=`<div class="metrics">${metric("ファイル",int(raw.sources.length))}${metric("Library",`${int(data.tracks.length)}曲`)}${metric("Events",int(data.playEvents.length))}${metric("Features",int(data.features.length))}</div><article class="panel">${raw.sources.map(s=>`<div class="source-card"><strong>${esc(s.filename)}</strong><span>${esc(names[s.kind]||s.kind)}</span><span class="muted">${int(s.count)}件</span></div>`).join('')}</article>`}
  function renderImport(){if(!imports.length){$("importView").innerHTML='<article class="panel"><h2>読み込み履歴</h2><p class="empty">このページで読み込んだファイルが表示されます。</p></article>';return}$("importView").innerHTML=`<article class="panel"><h2>読み込み履歴</h2>${table([{key:"name",label:"ファイル"},{key:"kind",label:"種類"},{key:"count",label:"件数",num:1,render:int},{key:"status",label:"結果"}],imports)}</article>`}
  async function load(files){const failures=[];for(const file of files){try{if(!file.name.toLowerCase().endsWith(".json"))throw new Error("JSONファイルではありません。");const parsed=A.parseDocument(JSON.parse(await file.text()),file.name);A.merge(raw,parsed);imports.unshift({name:file.name,kind:parsed.kind,count:parsed.items.length,status:"読み込み済み"})}catch(e){failures.push(`${file.name}: ${e instanceof SyntaxError?"JSON形式が不正です。":e.message}`);imports.unshift({name:file.name,kind:"—",count:0,status:"エラー"})}}data=A.normalize(raw);$("data-summary").hidden=!raw.sources.length;$("sourceSummary").textContent=`${raw.sources.length}ファイル · ${data.tracks.length}曲 · ${data.playEvents.length}イベント（ブラウザ内のみ）`;$("global-error").hidden=!failures.length;$("global-error").textContent=failures.join("\n");render();showPage(raw.sources.length?"dashboard":"import")}
  function showPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===name));history.replaceState(null,"",`#${name}`)}
  function bindImportButtons(){$$(".open-import").forEach(b=>b.onclick=()=>showPage("import"))}
  function setPeriod(next,button){period=next;$$('.periods button').forEach(b=>b.classList.toggle('active',b===button));document.querySelector('.custom-period').hidden=next!=="custom";render()}
  $$('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('.periods button').forEach(b=>b.onclick=()=>setPeriod(b.dataset.period,b));$("fileInput").onchange=e=>load(e.target.files);$("fileInputMore").onchange=e=>load(e.target.files);$("startDate").onchange=render;$("endDate").onchange=render;$("resetButton").onclick=()=>location.reload();$("trackSearch").oninput=renderTracks;$("clearTrackSearch").onclick=()=>{$("trackSearch").value="";renderTracks()};$$('#rankingMetric button').forEach(b=>b.onclick=()=>{rankingMetric=b.dataset.metric;$$('#rankingMetric button').forEach(x=>x.classList.toggle('active',x===b));renderRankings()});
  const drop=$("drop-zone");["dragenter","dragover"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add("drag")}));["dragleave","drop"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove("drag")}));drop.addEventListener("drop",e=>load(e.dataTransfer.files));
  showPage(location.hash.slice(1)&&$(location.hash.slice(1))?location.hash.slice(1):"dashboard");bindImportButtons();renderImport();
})();
