const state={dashboardPeriod:'7d',tracksPeriod:'all',tracksSort:'playCount',tracksOrder:'desc',tracksPage:1,sourceKind:'track_features',sourcesPage:1,sourceSort:'title',sourceOrder:'asc'};
const rankLimits={"#top-tracks":10,"#skipped-tracks":10,"#artists":10};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const duration=s=>{s=Math.round(Number(s)||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}時間 ${m}分`:`${m}分`};
const playbackDuration=s=>s==null?'データなし':duration(s);
const percent=v=>v==null?'—':`${Number(v).toFixed(1)}%`;
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function initializeCustomPeriod(prefix){const start=$(`#${prefix}-start-date`),end=$(`#${prefix}-end-date`);if(start.value&&end.value)return;const last=new Date(),first=new Date();first.setDate(last.getDate()-6);start.value=localDate(first);end.value=localDate(last)}
const kindLabel=k=>({playback_events:'再生イベント',library:'Library',playback_preferences:'再生傾向',track_features:'音楽特徴量',volume_normalization:'音量ノーマライズ',playlists:'プレイリスト',equalizer:'イコライザー',genre_presets:'ジャンルプリセット',unknown:'不明'}[k]||k);
async function api(url,options){const r=await fetch(url,options);if(!r.ok){let d;try{d=await r.json()}catch{d={}}throw new Error(d.detail||`HTTP ${r.status}`)}return r.json()}
function empty(text='データがありません'){return `<p class="empty">${text}</p>`}
async function loadDashboard(){
  const params=new URLSearchParams({period:state.dashboardPeriod});if(state.dashboardPeriod==='custom'){params.set('startDate',$('#dashboard-start-date').value.trim());params.set('endDate',$('#dashboard-end-date').value.trim())}
  const error=$('#dashboard-period-error');error.textContent='';let d;try{d=await api(`/api/dashboard?${params}`)}catch(e){error.textContent=e.message;return}const m=d.metrics;
  $('#metrics').innerHTML=[
    ['Library',`${Number(m.library_count).toLocaleString()}曲`],['再生回数',`${Number(m.play_count).toLocaleString()}回`],
    ['総再生時間',playbackDuration(m.total_play_time)],['Skip率',percent(m.skip_rate)],['完走率',percent(m.completion_rate)],
    ['お気に入り',`${Number(m.favorite_count).toLocaleString()}曲`],['Good / Badあり',`${Number(m.rated_count).toLocaleString()}曲`]
  ].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  const legacyNote=$('#dashboard-legacy-note'),hasLegacy=m.play_count>m.detail_event_count;legacyNote.hidden=!hasLegacy;legacyNote.textContent=hasLegacy?`※ ${d.legacyPlaybackCutoff}より前の再生は再生回数に含め、総再生時間・完走率・Skip率から除外しています。`:'';
  renderBars('#daily',d.daily);renderHours(d.hourly);renderRanks('#top-tracks',d.topTracks);
  renderRanks('#skipped-tracks',d.skippedTracks);renderRanks('#artists',d.artists,true);
  renderRanks('#preferences',d.preferenceDistribution,true);
}
function renderBars(sel,rows){if(!rows.length){$(sel).innerHTML=empty();return}const max=Math.max(...rows.map(x=>x.value),1);$(sel).innerHTML=rows.map(x=>`<div class="bar-item"><strong>${x.value}</strong><div class="bar" style="--height:${Math.max(4,x.value/max*78)}%" data-tip="${esc(x.label)}: ${x.value}回"></div><span>${esc(x.label.slice(5).replace('-','/'))}</span></div>`).join('')}
function renderHours(rows){const map=Object.fromEntries(rows.map(x=>[x.label,x.value])),max=Math.max(...Object.values(map),1);$('#hourly').innerHTML=Array.from({length:24},(_,h)=>`<div class="hour" style="--level:${(map[h]||0)/max}" data-tip="${h}時: ${map[h]||0}回" tabindex="0" aria-label="${h}時: ${map[h]||0}回">${h}</div>`).join('')}
function renderRanks(sel,rows,labelOnly=false){if(!rows.length){$(sel).innerHTML=empty();return}const limit=rankLimits[sel]||rows.length,visible=rows.slice(0,limit);$(sel).innerHTML=visible.map((x,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div><strong title="${esc(labelOnly?x.label:x.title)}">${esc(labelOnly?x.label:x.title)}</strong>${labelOnly?'':`<small title="${esc(x.artist)}">${esc(x.artist)}</small>`}</div><span>${x.value}${labelOnly?'曲':'回'}</span></div>`).join('')+(rows.length>10?`<button class="rank-more" data-rank="${sel}">${limit<rows.length?'続きを見る': '閉じる'}</button>`:'');const button=$(sel).querySelector('.rank-more');if(button)button.onclick=()=>{rankLimits[sel]=limit<rows.length?Math.min(limit+10,50):10;renderRanks(sel,rows,labelOnly)}}
function renderPagination(selector,page,total,pageSize,load){const pages=Math.max(1,Math.ceil(total/pageSize)),root=$(selector);root.innerHTML=total>pageSize?`<button data-page="prev" ${page<=1?'disabled':''}>前へ</button><span>${page} / ${pages}ページ（${Number(total).toLocaleString()}件）</span><button data-page="next" ${page>=pages?'disabled':''}>次へ</button>`:'';root.querySelectorAll('button').forEach(button=>button.onclick=()=>load(button.dataset.page==='prev'?page-1:page+1))}
function preference(value){if(value==null)return '<span class="preference">未取込</span>';const cls=value>0?'good':value<0?'bad':'';return `<span class="preference ${cls}">${value>0?'+':''}${value}</span>`}
function preferenceEditor(x){if(x.playbackPreference==null)return preference(null);return `<select class="preference-editor" data-track-id="${esc(x.trackId)}" aria-label="${esc(x.title)}のGood / Bad">${Array.from({length:21},(_,i)=>i-10).map(v=>`<option value="${v}" ${v===x.playbackPreference?'selected':''}>${v>0?'+':''}${v}</option>`).join('')}</select>`}
function favoriteEditor(x){if(x.playbackPreference==null)return `<span class="favorite">${x.favorite===1?'♥':'—'}</span>`;return `<button class="favorite-editor ${x.favorite===1?'active':''}" data-track-id="${esc(x.trackId)}" data-favorite="${x.favorite===1}" aria-label="${esc(x.title)}のお気に入り">${x.favorite===1?'♥':'♡'}</button>`}
async function loadTracks(){
  const params=new URLSearchParams({period:state.tracksPeriod,sort:state.tracksSort,order:state.tracksOrder,page:state.tracksPage});
  [['title','#track-title'],['artist','#track-artist'],['album','#track-album'],['genre','#track-genre']].forEach(([key,selector])=>{const v=$(selector).value.trim();if(v)params.set(key,v)});
  if(state.tracksPeriod==='custom'){params.set('startDate',$('#track-start-date').value);params.set('endDate',$('#track-end-date').value)}
  const error=$('#period-error');error.textContent='';
  let d;try{d=await api(`/api/tracks?${params}`)}catch(e){error.textContent=e.message;$('#tracks-body').innerHTML=`<tr><td colspan="11">${empty('期間を確認してください')}</td></tr>`;return}
  $$('.sort-button').forEach(button=>{const active=button.dataset.sort===state.tracksSort;button.classList.toggle('active',active);button.setAttribute('aria-sort',active?(state.tracksOrder==='asc'?'ascending':'descending'):'none');button.dataset.indicator=active?(state.tracksOrder==='asc'?'↑':'↓'):''});
  $('#tracks-body').innerHTML=d.tracks.length?d.tracks.map(x=>`<tr>
    <td title="${esc(x.title)}"><strong>${esc(x.title)}</strong><small>${x.genre?esc(x.genre):'—'}${x.inLibrary?'':' · 履歴のみ'}</small></td><td title="${esc(x.artist)}">${esc(x.artist)||'—'}</td><td title="${esc(x.album)}">${esc(x.album)||'—'}</td>
    <td>${preferenceEditor(x)}</td><td>${favoriteEditor(x)}</td><td>${x.hasFingerprint?'✓':'—'}</td>
    <td>${x.playCount}回</td><td>${playbackDuration(x.totalPlayTime)}</td><td>${percent(x.completionRate)}</td><td>${percent(x.skipRate)}</td>
    <td>${x.lastPlayedAt?new Date(x.lastPlayedAt).toLocaleString('ja-JP'):'—'}</td></tr>`).join(''):`<tr><td colspan="11">${empty()}</td></tr>`;
  $$('.preference-editor').forEach(el=>el.onchange=()=>savePreference(el.dataset.trackId,Number(el.value),favoriteValue(el.dataset.trackId)));
  $$('.favorite-editor').forEach(el=>el.onclick=()=>savePreference(el.dataset.trackId,preferenceValue(el.dataset.trackId),el.dataset.favorite!=='true'));
  renderPagination('#tracks-pagination',d.page,d.total,d.pageSize,page=>{state.tracksPage=page;loadTracks()});
}
function preferenceValue(trackId){return Number($(`.preference-editor[data-track-id="${CSS.escape(trackId)}"]`).value)}
function favoriteValue(trackId){return $(`.favorite-editor[data-track-id="${CSS.escape(trackId)}"]`).dataset.favorite==='true'}
async function savePreference(trackId,playbackPreference,favorite){try{await api(`/api/preferences/${encodeURIComponent(trackId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({playbackPreference,favorite})});await Promise.all([loadTracks(),loadDashboard()])}catch(e){alert(`再生傾向を保存できませんでした: ${e.message}`);await loadTracks()}}
const value=(v,digits=2)=>v==null?'—':Number(v).toFixed(digits);
async function loadSources(){
  const d=await api(`/api/sources/${state.sourceKind}?page=${state.sourcesPage}&sort=${state.sourceSort}&order=${state.sourceOrder}`),trackKind=['track_features','volume_normalization'].includes(state.sourceKind);
  $('#source-summary').innerHTML=[['データ種別',kindLabel(state.sourceKind)],['登録項目',`${d.count}件`],...(trackKind?[['Library紐付け',`${d.linkedCount} / ${d.count}曲`]]:[])].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  const configs={track_features:{head:['曲','Library','Tempo','Energy','Vocal','解析Version'],row:x=>[`${esc(x.title)}<small>${esc(x.subtitle||'')}</small>`,x.linked?'✓':'未紐付け',value(x.data.features?.tempo,1),value(x.data.features?.energy),value(x.data.features?.vocal),x.data.analysisVersion]},volume_normalization:{head:['曲','Library','Integrated LUFS','True Peak','補正Gain','相対パス'],row:x=>[`${esc(x.title)}<small>${esc(x.subtitle||'')}</small>`,x.linked?'✓':'未紐付け',value(x.data.integratedLUFS,1),value(x.data.truePeakDBTP,1),value(x.data.normalizationGainDB,1),esc(x.data.relativePath)]},playlists:{head:['プレイリスト','種類','タグ','収録曲','Library紐付け','更新日時'],row:x=>[esc(x.title),esc(x.data.kind),esc((x.data.tags||[]).join(', ')||'—'),`${x.trackCount}曲`,`${x.linkedTrackCount} / ${x.trackCount}`,x.data.updatedAt?new Date(x.data.updatedAt).toLocaleString('ja-JP'):'—']},equalizer:{head:['設定 / プリセット','区分','有効','Preamp','Band Gain'],row:x=>[esc(x.title),esc(x.data.recordType),x.data.isEnabled==null?'—':(x.data.isEnabled?'ON':'OFF'),value(x.data.preamp,1),esc((x.data.gains||x.data.bands?.map(b=>b.gain)||[]).join(', '))]},genre_presets:{head:['プリセット','有効ジャンル数','ジャンル','未分類設定'],row:x=>[esc(x.title),(x.data.enabledGenreNames||[]).length,esc((x.data.enabledGenreNames||[]).join(', ')||'—'),x.data.includesUnassignedGenreSetting==null?'既定':(x.data.includesUnassignedGenreSetting?'含む':'含まない')]}};
  const c=configs[state.sourceKind];$('#sources-head').innerHTML=`<tr>${c.head.map(x=>`<th>${x}</th>`).join('')}</tr>`;$('#sources-body').innerHTML=d.items.length?d.items.map(x=>`<tr>${c.row(x).map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${c.head.length}">${empty('このJSONはまだImportされていません')}</td></tr>`;
  renderPagination('#sources-pagination',d.page,d.count,d.pageSize,page=>{state.sourcesPage=page;loadSources()});
}
async function loadImports(){const d=await api('/api/imports');$('#imports-body').innerHTML=d.imports.length?d.imports.map(x=>`<tr><td>${new Date(x.importedAt).toLocaleString('ja-JP')}<small>${esc(x.sourceFilename)}</small></td><td>${esc(kindLabel(x.dataKind))}</td><td>${x.newCount}</td><td>${x.updatedCount}</td><td>${x.duplicateCount}</td><td>${x.errorCount}</td></tr>`).join(''):`<tr><td colspan="6">${empty('Import履歴はまだありません')}</td></tr>`}
async function upload(file){if(!file)return;const zone=$('#drop-zone'),result=$('#import-result');zone.querySelector('strong').textContent='Import中…';try{const form=new FormData();form.append('file',file);const d=await api('/api/import',{method:'POST',body:form});result.innerHTML=`<p class="subtitle">${esc(kindLabel(d.dataKind))}としてImportしました。</p><div class="result"><div><strong>${d.newCount}</strong><span>新規</span></div><div><strong>${d.updatedCount}</strong><span>更新</span></div><div><strong>${d.duplicateCount}</strong><span>重複</span></div><div><strong>${d.errorCount}</strong><span>エラー</span></div></div>${d.errors.length?`<p class="subtitle">${d.errors.map(esc).join('<br>')}</p>`:''}`;await Promise.all([loadImports(),loadDashboard()])}catch(e){result.innerHTML=`<p class="subtitle">Importできませんでした: ${esc(e.message)}</p>`}finally{zone.querySelector('strong').textContent='JSONをここへドロップ';$('#file-input').value=''}}
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.page}`).classList.add('active');if(b.dataset.page==='tracks')loadTracks();if(b.dataset.page==='sources')loadSources();if(b.dataset.page==='import')loadImports()});
$$('#source-tabs button').forEach(b=>b.onclick=()=>{$$('#source-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sourceKind=b.dataset.kind;state.sourcesPage=1;loadSources()});
$$('.periods button').forEach(b=>b.onclick=()=>{const group=b.closest('.periods');group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(group.dataset.target==='dashboard'){state.dashboardPeriod=b.dataset.period;$('#dashboard-custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('dashboard');Object.keys(rankLimits).forEach(key=>rankLimits[key]=10);loadDashboard()}else{state.tracksPeriod=b.dataset.period;state.tracksPage=1;$('#custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('track');loadTracks()}});
let searchTimer;$$('.track-filters input').forEach(input=>input.oninput=()=>{clearTimeout(searchTimer);state.tracksPage=1;searchTimer=setTimeout(loadTracks,250)});
$$('#custom-period input').forEach(input=>input.onchange=()=>{state.tracksPage=1;loadTracks()});
$$('#dashboard-custom-period input').forEach(input=>input.onchange=loadDashboard);
$('#clear-track-filters').onclick=()=>{$$('.track-filters input').forEach(input=>input.value='');state.tracksPage=1;loadTracks()};
$$('.sort-button').forEach(button=>button.onclick=()=>{if(state.tracksSort===button.dataset.sort)state.tracksOrder=state.tracksOrder==='asc'?'desc':'asc';else{state.tracksSort=button.dataset.sort;state.tracksOrder='asc'}state.tracksPage=1;loadTracks()});
$('#source-sort').onchange=e=>{state.sourceSort=e.target.value;state.sourcesPage=1;loadSources()};
$('#source-order').onclick=e=>{state.sourceOrder=state.sourceOrder==='asc'?'desc':'asc';e.currentTarget.textContent=state.sourceOrder==='asc'?'昇順 ↑':'降順 ↓';state.sourcesPage=1;loadSources()};
$('#file-input').onchange=e=>upload(e.target.files[0]);const zone=$('#drop-zone');['dragenter','dragover'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>upload(e.dataTransfer.files[0]));
loadDashboard();
