const state={dashboardPeriod:'7d',historyMonth:null,historyTab:'daily',insightsPeriod:'7d',insightsQuality:'analyzable',insightFeature:'dark',insightsTab:'recommendations',rankingsPeriod:'30d',rankingMetric:'plays',rankingArtist:'',rankingGenre:'',rankingFiltersLoaded:false,tracksPeriod:'all',tracksSort:'playCount',tracksOrder:'desc',tracksPage:1,sourceKind:'track_features',sourcesPage:1,sourceSort:'title',sourceOrder:'asc'};
const progressiveListPolicy=Object.freeze({initial:30,step:30});
const progressiveListLimits={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const duration=s=>{s=Math.round(Number(s)||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}時間 ${m}分`:`${m}分`};
const playbackDuration=s=>s==null?'データなし':duration(s);
const percent=v=>v==null?'—':`${Number(v).toFixed(1)}%`;
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function initializeCustomPeriod(prefix){const start=$(`#${prefix}-start-date`),end=$(`#${prefix}-end-date`);if(start.value&&end.value)return;const last=new Date(),first=new Date();first.setDate(last.getDate()-6);start.value=localDate(first);end.value=localDate(last)}
const kindLabel=k=>({playback_events:'再生イベント',library:'Library',playback_preferences:'再生傾向',track_features:'音楽特徴量',volume_normalization:'音量ノーマライズ',playlists:'プレイリスト',equalizer:'イコライザー',library_genres:'ジャンル（Library集計）',genre_presets:'ジャンルプリセット',unknown:'不明'}[k]||k);
async function api(url,options){const r=await fetch(url,options);if(!r.ok){let d;try{d=await r.json()}catch{d={}}throw new Error(d.detail||`HTTP ${r.status}`)}return r.json()}
function empty(text='データがありません'){return `<p class="empty">${text}</p>`}
const weekdayLabels=['日','月','火','水','木','金','土'];
const dateKey=(year,month,day)=>`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
const calendarDay=(year,month,day)=>new Date(Date.UTC(year,month-1,day)).getUTCDay();
const nthMonday=(year,month,n)=>{const first=calendarDay(year,month,1);return 1+((8-first)%7)+(n-1)*7};
function japaneseHolidays(year){
  const holidays=new Set(),add=(month,day)=>holidays.add(dateKey(year,month,day));
  add(1,1);add(1,nthMonday(year,1,2));add(2,11);if(year>=2020)add(2,23);
  add(3,Math.floor(20.8431+.242194*(year-1980)-Math.floor((year-1980)/4)));
  add(4,29);add(5,3);add(5,4);add(5,5);add(7,nthMonday(year,7,3));add(8,11);
  add(9,nthMonday(year,9,3));add(9,Math.floor(23.2488+.242194*(year-1980)-Math.floor((year-1980)/4)));
  add(10,nthMonday(year,10,2));add(11,3);add(11,23);
  if(year<=2018)add(12,23);
  if(year===2019){add(4,30);add(5,1);add(5,2);add(10,22)}
  if(year===2020){holidays.delete(dateKey(year,7,nthMonday(year,7,3)));holidays.delete(dateKey(year,8,11));holidays.delete(dateKey(year,10,nthMonday(year,10,2)));add(7,23);add(7,24);add(8,10)}
  if(year===2021){holidays.delete(dateKey(year,7,nthMonday(year,7,3)));holidays.delete(dateKey(year,8,11));holidays.delete(dateKey(year,10,nthMonday(year,10,2)));add(7,22);add(7,23);add(8,8)}
  [...holidays].sort().forEach(key=>{const [y,m,d]=key.split('-').map(Number);if(calendarDay(y,m,d)!==0)return;const next=new Date(Date.UTC(y,m-1,d+1));let substitute=dateKey(next.getUTCFullYear(),next.getUTCMonth()+1,next.getUTCDate());while(holidays.has(substitute)){next.setUTCDate(next.getUTCDate()+1);substitute=dateKey(next.getUTCFullYear(),next.getUTCMonth()+1,next.getUTCDate())}holidays.add(substitute)});
  for(let cursor=new Date(Date.UTC(year,0,2));cursor.getUTCFullYear()===year;cursor.setUTCDate(cursor.getUTCDate()+1)){const key=dateKey(year,cursor.getUTCMonth()+1,cursor.getUTCDate());if(holidays.has(key))continue;const previous=new Date(cursor);previous.setUTCDate(previous.getUTCDate()-1);const next=new Date(cursor);next.setUTCDate(next.getUTCDate()+1);const previousKey=dateKey(previous.getUTCFullYear(),previous.getUTCMonth()+1,previous.getUTCDate()),nextKey=dateKey(next.getUTCFullYear(),next.getUTCMonth()+1,next.getUTCDate());if(holidays.has(previousKey)&&holidays.has(nextKey))holidays.add(key)}
  return holidays;
}
const holidayCache=new Map();
function dayPresentation(label){const [year,month,day]=label.split('-').map(Number),weekday=calendarDay(year,month,day);if(!holidayCache.has(year))holidayCache.set(year,japaneseHolidays(year));const holiday=holidayCache.get(year).has(label);return {weekday,label:weekdayLabels[weekday],holiday,kind:holiday||weekday===0?'holiday':weekday===6?'saturday':''}}
function filterDashboardToDate(label){state.dashboardPeriod='custom';$('#dashboard-start-date').value=label;$('#dashboard-end-date').value=label;$('#dashboard-custom-period').hidden=false;const group=$('.periods[data-target="dashboard"]');group.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.period==='custom'));Object.keys(progressiveListLimits).forEach(key=>delete progressiveListLimits[key]);loadDashboard()}
async function loadDashboard(){
  const params=new URLSearchParams({period:state.dashboardPeriod});if(state.dashboardPeriod==='custom'){params.set('startDate',$('#dashboard-start-date').value.trim());params.set('endDate',$('#dashboard-end-date').value.trim())}
  const error=$('#dashboard-period-error');error.textContent='';let d;try{d=await api(`/api/dashboard?${params}`)}catch(e){error.textContent=e.message;return}const m=d.metrics;
  $('#metrics').innerHTML=[
    ['Library',`${Number(m.library_count).toLocaleString()}曲`],['再生回数',`${Number(m.play_count).toLocaleString()}回`],
    ['総再生時間',playbackDuration(m.total_play_time)],['Skip率',percent(m.skip_rate)],['完走率',percent(m.completion_rate)],
    ['Early Skip',`${Number(m.early_skip_count).toLocaleString()}回`],['Early Skip率',percent(m.early_skip_rate)],
    ['お気に入り',`${Number(m.favorite_count).toLocaleString()}曲`],['Good / Badあり',`${Number(m.rated_count).toLocaleString()}曲`]
  ].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  const legacyNote=$('#dashboard-legacy-note'),hasLegacy=m.play_count>m.detail_event_count;legacyNote.hidden=!hasLegacy;legacyNote.textContent=hasLegacy?`※ ${d.legacyPlaybackCutoff}より前の再生は再生回数に含め、総再生時間・完走率・Skip率から除外しています。`:'';
  renderBars('#daily',d.daily);renderHours(d.hourly);renderRanks('#top-tracks',d.topTracks);
  renderRanks('#skipped-tracks',d.skippedTracks);renderEarlySkipRanks(d.earlySkippedTracks);renderRanks('#artists',d.artists,true);
  renderRanks('#preferences',d.preferenceDistribution,true);
}
function renderBars(sel,rows){if(!rows.length){$(sel).innerHTML=empty();return}const max=Math.max(...rows.map(x=>x.value),1);$(sel).innerHTML=rows.map(x=>{const day=dayPresentation(x.label),description=`${x.label}（${day.label}${day.holiday?'・祝日':''}）: ${x.value}回`;return `<button type="button" class="bar-item ${day.kind}" data-date="${esc(x.label)}" aria-label="${esc(description)}。この日だけを表示"><strong>${x.value}</strong><span class="bar" style="--height:${Math.max(4,x.value/max*78)}%" data-tip="${esc(description)}"></span><span class="bar-date">${esc(x.label.slice(5).replace('-','/'))}</span><span class="bar-weekday">${day.label}</span></button>`}).join('');$(sel).querySelectorAll('.bar-item').forEach(item=>item.onclick=()=>filterDashboardToDate(item.dataset.date))}
function renderHours(rows){const map=Object.fromEntries(rows.map(x=>[x.label,x.value])),max=Math.max(...Object.values(map),1);$('#hourly').innerHTML=Array.from({length:24},(_,h)=>`<div class="hour" style="--level:${(map[h]||0)/max}" data-tip="${h}時: ${map[h]||0}回" tabindex="0" aria-label="${h}時: ${map[h]||0}回">${h}</div>`).join('')}
function renderRanks(sel,rows,labelOnly=false){renderProgressiveList(sel,rows,(x,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div><strong title="${esc(labelOnly?x.label:x.title)}">${esc(labelOnly?x.label:x.title)}</strong>${labelOnly?'':`<small title="${esc(x.artist)}">${esc(x.artist)}</small>`}</div><span>${x.value}${labelOnly?'曲':'回'}</span></div>`)}
function renderEarlySkipRanks(rows){renderProgressiveList('#early-skipped-tracks',rows,(x,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div><strong title="${esc(x.title)}">${esc(x.title)}</strong><small title="${esc(x.artist)}">${esc(x.artist)}</small><small>総再生 ${Number(x.totalPlayCount).toLocaleString()}回 · ${percent(x.earlySkipRate)}</small></div><span>${x.earlySkipCount}回</span></div>`)}
async function loadMusicHistory(){const d=await api('/api/music-history'),root=$('#history-timeline');state.historyMonth=null;renderProgressiveList('#history-timeline',d.months,x=>`<article class="history-card" data-history-month="${esc(x.month)}" role="button" tabindex="0" aria-expanded="false"><time>${esc(x.month.replace('-', ' / '))}</time><div class="history-stats"><strong>${Number(x.playCount).toLocaleString()}<small>再生</small></strong><strong>${playbackDuration(x.detailEventCount?x.totalPlayTime:null)}<small>再生時間</small></strong></div><div class="history-highlights"><div><span>この月の曲</span><strong>${esc(x.topTrack.title)}</strong><small>${esc(x.topTrack.artist)} · ${x.topTrack.value}回</small></div><div><span>この月のArtist</span><strong>${esc(x.topArtist.name)}</strong><small>${x.topArtist.value}回</small></div></div><span class="history-expand-hint">詳細を見る</span></article>`,'再生履歴をImportすると、ここに音楽史が育っていきます。');root.onclick=event=>{if(event.target.closest('.rank-more')){state.historyMonth=null;return}const card=event.target.closest('[data-history-month]');if(card)toggleHistoryMonth(card.dataset.historyMonth)};root.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-history-month]')){event.preventDefault();toggleHistoryMonth(event.target.dataset.historyMonth)}};const hasLegacy=d.months.some(x=>x.playCount>x.detailEventCount),note=$('#history-legacy-note');note.hidden=!hasLegacy;note.textContent=hasLegacy?`※ ${d.legacyPlaybackCutoff}より前の月は、再生回数のみ正確です。`:''}
function monthDates(month){const [year,value]=month.split('-').map(Number),last=new Date(Date.UTC(year,value,0)).getUTCDate();return {start:`${month}-01`,end:`${month}-${String(last).padStart(2,'0')}`}}
function previousMonth(month){const [year,value]=month.split('-').map(Number),date=new Date(Date.UTC(year,value-2,1));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`}
function historyPeriodParams(month){const range=monthDates(month);return new URLSearchParams({period:'custom',startDate:range.start,endDate:range.end})}
function toggleHistoryMonth(month){if(state.historyMonth===month){state.historyMonth=null;$('#history-detail')?.remove();$$('[data-history-month]').forEach(card=>{card.setAttribute('aria-expanded','false');card.querySelector('.history-expand-hint').textContent='詳細を見る'});return}state.historyMonth=month;state.historyTab='daily';$$('[data-history-month]').forEach(card=>{const active=card.dataset.historyMonth===month;card.setAttribute('aria-expanded',String(active));card.querySelector('.history-expand-hint').textContent=active?'詳細を閉じる':'詳細を見る'});const card=$(`[data-history-month="${CSS.escape(month)}"]`),detail=document.createElement('section');detail.id='history-detail';detail.className='history-detail';detail.innerHTML=`<div class="content-tabs history-detail-tabs" role="tablist" aria-label="${esc(month)}の詳細"><button class="active" data-history-tab="daily">日ごと</button><button data-history-tab="rankings">ランキング</button><button data-history-tab="reflection">振り返り</button></div><div id="history-detail-body"><p class="empty">読み込み中…</p></div>`;$('#history-detail')?.remove();card.insertAdjacentElement('afterend',detail);detail.querySelectorAll('[data-history-tab]').forEach(button=>button.onclick=()=>showHistoryTab(button.dataset.historyTab));showHistoryTab('daily')}
async function showHistoryTab(tab){state.historyTab=tab;$$('[data-history-tab]').forEach(button=>{const active=button.dataset.historyTab===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});const body=$('#history-detail-body');body.innerHTML='<p class="empty">読み込み中…</p>';try{if(tab==='daily')await renderHistoryDaily(body,state.historyMonth);else if(tab==='rankings')await renderHistoryRankings(body,state.historyMonth);else await renderHistoryReflection(body,state.historyMonth)}catch(error){body.innerHTML=empty(error.message)}}
async function renderHistoryDaily(body,month){const d=await api(`/api/dashboard?${historyPeriodParams(month)}`),max=Math.max(...d.daily.map(x=>x.value),1);body.innerHTML=`<h3>${esc(month.replace('-', ' / '))}の日ごとの再生</h3><div class="bar-chart history-daily-chart">${d.daily.map(x=>{const day=dayPresentation(x.label),description=`${x.label}: ${x.value}回`;return `<button type="button" class="bar-item ${day.kind}" data-history-date="${esc(x.label)}" aria-label="${esc(description)}"><strong>${x.value}</strong><span class="bar" style="--height:${Math.max(4,x.value/max*110)}%"></span><span class="bar-date">${Number(x.label.slice(8))}</span><span class="bar-weekday">${day.label}</span></button>`}).join('')}</div><div id="history-day-detail">${empty('日付を選ぶと、その日の再生曲を表示します。')}</div>`;body.querySelectorAll('[data-history-date]').forEach(button=>button.onclick=()=>renderHistoryDay(button.dataset.historyDate))}
async function renderHistoryDay(date){const params=new URLSearchParams({period:'custom',startDate:date,endDate:date,sort:'playCount',order:'desc',page:'1'}),d=await api(`/api/tracks?${params}`),root=$('#history-day-detail');root.innerHTML=`<div class="history-day-heading"><h3>${esc(date)}の再生曲</h3><button type="button" id="history-open-tracks">Tracksで全件見る</button></div>${d.tracks.length?d.tracks.map((x,index)=>`<div class="rank-row"><span class="rank">${index+1}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.artist||'')}</small></div><span>${x.playCount}回</span></div>`).join(''):empty('この日の再生はありません')}`;$('#history-open-tracks').onclick=()=>{state.tracksPeriod='custom';$('#track-start-date').value=date;$('#track-end-date').value=date;$('#custom-period').hidden=false;$('.periods[data-target="tracks"]').querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.period==='custom'));state.tracksPage=1;navigate('tracks')};}
async function renderHistoryRankings(body,month){const dimensions=[['tracks','曲'],['artists','Artist'],['albums','Album'],['genres','Genre']],base=historyPeriodParams(month);base.set('metric','plays');dimensions.forEach(([dimension])=>delete progressiveListLimits[`#history-ranking-${dimension}`]);const results=await Promise.all(dimensions.map(([dimension])=>{const params=new URLSearchParams(base);params.set('dimension',dimension);return api(`/api/rankings?${params}`)}));body.innerHTML=`<div class="history-ranking-columns">${dimensions.map(([dimension,label])=>`<article class="panel"><h3>${label}</h3><div id="history-ranking-${dimension}"></div></article>`).join('')}</div>`;results.forEach((d,index)=>renderProgressiveList(`#history-ranking-${dimensions[index][0]}`,d.items,(x,position)=>`<div class="rank-row"><span class="rank">${position+1}</span><div><strong>${esc(x.label)}</strong>${x.subtitle?`<small>${esc(x.subtitle)}</small>`:''}</div><span>${Number(x.value).toLocaleString()}回</span></div>`))}
async function renderHistoryReflection(body,month){const currentParams=historyPeriodParams(month),prior=previousMonth(month),previousParams=historyPeriodParams(prior),[current,previous]=await Promise.all([api(`/api/dashboard?${currentParams}`),api(`/api/dashboard?${previousParams}`)]),metric=(label,currentValue,previousValue,format=value=>Number(value).toLocaleString())=>{const delta=previousValue?((currentValue-previousValue)/previousValue*100):null;return `<div class="metric"><span>${label}</span><strong>${format(currentValue)}</strong><small>${delta==null?'前月比—':`前月比 ${delta>=0?'+':''}${delta.toFixed(1)}%`}</small></div>`};body.innerHTML=`<h3>${esc(month.replace('-', ' / '))}の振り返り</h3><div class="metrics history-reflection">${metric('再生回数',current.metrics.play_count,previous.metrics.play_count,value=>`${Number(value).toLocaleString()}回`)}${metric('再生時間',current.metrics.total_play_time||0,previous.metrics.total_play_time||0,playbackDuration)}${metric('完走率',current.metrics.completion_rate||0,previous.metrics.completion_rate||0,value=>percent(value))}${metric('Skip率',current.metrics.skip_rate||0,previous.metrics.skip_rate||0,value=>percent(value))}</div><div class="history-reflection-highlights"><article class="panel"><span>最も聴いた曲</span><strong>${esc(current.topTracks[0]?.title||'—')}</strong><small>${esc(current.topTracks[0]?.artist||'')}</small></article><article class="panel"><span>最も聴いたArtist</span><strong>${esc(current.artists[0]?.label||'—')}</strong><small>${current.artists[0]?`${current.artists[0].value}曲`:'—'}</small></article></div>`}
const insightCount=v=>v==null?'—':`${Number(v).toLocaleString()}回`;
function sortableCell(value,html=value){return `<td data-sort-value="${esc(value??'')}">${html}</td>`}
function insightRows(rows,dimensions){return rows.length?rows.map(x=>`<tr>${dimensions.map(key=>sortableCell(x[key],`<strong>${esc(x[key])}</strong>`)).join('')}${sortableCell(x.playCount,`${Number(x.playCount).toLocaleString()}回`)}${sortableCell(x.totalPlayTime,playbackDuration(x.totalPlayTime))}${sortableCell(x.completionRate,percent(x.completionRate))}${sortableCell(x.skipRate,percent(x.skipRate))}${sortableCell(x.earlySkipCount,insightCount(x.earlySkipCount))}${sortableCell(x.earlySkipRate,percent(x.earlySkipRate))}</tr>`).join(''):`<tr><td colspan="${dimensions.length+6}">${empty()}</td></tr>`}
function initializeSortableTables(){$$('table[data-sortable]').forEach(table=>{table.querySelectorAll('thead th').forEach((heading,index)=>{const label=heading.textContent;heading.innerHTML=`<button type="button" class="sort-button" data-table-column="${index}">${esc(label)}</button>`});table.querySelectorAll('[data-table-column]').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.tableColumn),ascending=button.dataset.order!=='asc',body=table.tBodies[0],rows=[...body.rows].filter(row=>row.cells.length>index&&row.cells[index].dataset.sortValue!==undefined);rows.sort((a,b)=>{const left=a.cells[index].dataset.sortValue,right=b.cells[index].dataset.sortValue,leftNumber=Number(left),rightNumber=Number(right),comparison=left!==''&&right!==''&&Number.isFinite(leftNumber)&&Number.isFinite(rightNumber)?leftNumber-rightNumber:left.localeCompare(right,'ja',{numeric:true,sensitivity:'base'});return ascending?comparison:-comparison});rows.forEach(row=>body.append(row));table.querySelectorAll('[data-table-column]').forEach(other=>{other.dataset.indicator='';other.removeAttribute('aria-sort')});button.dataset.order=ascending?'asc':'desc';button.dataset.indicator=ascending?'↑':'↓';button.setAttribute('aria-sort',ascending?'ascending':'descending')})})}
function insightsParams(){const params=new URLSearchParams({period:state.insightsPeriod,quality:state.insightsQuality});if(state.insightsPeriod==='custom'){params.set('startDate',$('#insights-start-date').value.trim());params.set('endDate',$('#insights-end-date').value.trim())}return params}
async function loadInsights(){const params=insightsParams(),error=$('#insights-period-error');error.textContent='';Object.keys(progressiveListLimits).forEach(key=>delete progressiveListLimits[key]);let d,changes,advanced,recommendations;try{[d,,changes,advanced,recommendations]=await Promise.all([api(`/api/insights?${params}`),loadFeatureInsights(params),api(`/api/insights/recent-changes?${params}`),api(`/api/insights/advanced?${params}`),api(`/api/insights/recommendations?${params}`)])}catch(e){error.textContent=e.message;return}$('#insights-source-body').innerHTML=insightRows(d.byPlaySource,['playSource']);$('#insights-selection-body').innerHTML=insightRows(d.bySelectionType,['selectionType']);$('#insights-combination-body').innerHTML=insightRows(d.combinations,['playSource','selectionType']);renderRecentChanges(changes);renderAdvancedInsights(advanced);renderRecommendations(recommendations);const hasLegacy=d.quality==='all'&&[...d.byPlaySource,...d.bySelectionType].some(x=>x.playCount>x.detailEventCount),note=$('#insights-legacy-note');note.hidden=!hasLegacy;note.textContent=hasLegacy?`※ ${d.legacyPlaybackCutoff}より前のイベントは再生回数だけに含め、その他の指標から除外しています。`:''}
function rateBar(value,kind){return `<span class="feature-rate ${kind}"><i style="--rate:${value==null?0:Math.max(0,Math.min(100,Number(value)))}%"></i><b>${percent(value)}</b></span>`}
async function loadFeatureInsights(existingParams){const params=existingParams?new URLSearchParams(existingParams):insightsParams();params.set('feature',state.insightFeature);const d=await api(`/api/insights/features?${params}`);$('#feature-version').textContent=d.analysisVersion==null?'解析データなし':`analysisVersion ${d.analysisVersion}`;$('#feature-behavior-body').innerHTML=d.bins.map(x=>`<tr>${sortableCell(x.lowerBound,`<strong>${esc(x.label)}</strong>`)}${sortableCell(x.trackCount,`${Number(x.trackCount).toLocaleString()}曲`)}${sortableCell(x.playCount,`${Number(x.playCount).toLocaleString()}回`)}${sortableCell(x.completionRate,rateBar(x.completionRate,'completion'))}${sortableCell(x.skipRate,rateBar(x.skipRate,'skip'))}${sortableCell(x.earlySkipRate,rateBar(x.earlySkipRate,'early'))}</tr>`).join('');return d}
function trackItem(x,detail){return `<button class="insight-track" data-track-title="${esc(x.title)}"><strong>${esc(x.title)}</strong><small>${esc(x.artist||'')} · ${esc(detail)}</small></button>`}
function renderChangeList(selector,rows,detail){renderProgressiveList(selector,rows,x=>trackItem(x,detail(x)),'今の条件では候補がありません')}
function renderProgressiveList(selector,rows,rowHTML,emptyText='データがありません'){
  const root=$(selector);if(!rows.length){root.innerHTML=empty(emptyText);return}
  const limit=progressiveListLimits[selector]||progressiveListPolicy.initial;
  root.innerHTML=rows.slice(0,limit).map(rowHTML).join('')+(rows.length>progressiveListPolicy.initial?`<button type="button" class="rank-more">${limit<rows.length?'続きを見る':'閉じる'}</button>`:'');
  const button=root.querySelector('.rank-more');if(button)button.onclick=()=>{progressiveListLimits[selector]=limit<rows.length?Math.min(limit+progressiveListPolicy.step,rows.length):progressiveListPolicy.initial;renderProgressiveList(selector,rows,rowHTML,emptyText)}
}
function renderProgressiveTable(bodySelector,controlSelector,rows,rowHTML,colspan,emptyText='データがありません'){const body=$(bodySelector),control=$(controlSelector);if(!rows.length){body.innerHTML=`<tr><td colspan="${colspan}">${empty(emptyText)}</td></tr>`;control.innerHTML='';return}const limit=progressiveListLimits[bodySelector]||progressiveListPolicy.initial;body.innerHTML=rows.slice(0,limit).map(rowHTML).join('');control.innerHTML=rows.length>progressiveListPolicy.initial?`<button type="button" class="rank-more">${limit<rows.length?'続きを見る':'閉じる'}</button>`:'';const button=control.querySelector('.rank-more');if(button)button.onclick=()=>{progressiveListLimits[bodySelector]=limit<rows.length?Math.min(limit+progressiveListPolicy.step,rows.length):progressiveListPolicy.initial;renderProgressiveTable(bodySelector,controlSelector,rows,rowHTML,colspan,emptyText)}}
function renderRecentChanges(d){$('#change-window').textContent=`最近 ${d.recentWindow.startDate}〜${d.recentWindow.endDate} / 比較 ${d.baselineWindow.startDate}〜${d.baselineWindow.endDate}`;renderChangeList('#hooked-tracks',d.hookedTracks,x=>`最近${x.recentPlayCount}回・過去${x.baselinePlayCount}回`);renderChangeList('#bored-tracks',d.boredTracks,x=>`Skip変化 ${x.skipRateDelta==null?'—':`${x.skipRateDelta.toFixed(1)}pt`}`);renderProgressiveList('#new-tastes',d.newTastes,x=>`<div class="insight-text"><strong>${esc(x.featureLabel)}</strong><small>完走率 ${x.completionRateDelta>=0?'+':''}${x.completionRateDelta.toFixed(1)}pt / Skip改善 ${x.skipRateImprovement.toFixed(1)}pt</small></div>`,'今の条件では候補がありません');renderChangeList('#rediscovery-tracks',d.rediscoveryTracks,x=>`以前${x.historicalDetailCount}回・完走率${x.historicalCompletionRate.toFixed(0)}%`);wireTrackLinks()}
function renderAdvancedInsights(d){const reliable=d.timeFeatureAffinity.filter(x=>x.isReliable),entities=Object.entries(d.entityChanges).flatMap(([kind,rows])=>rows.map(x=>({...x,kind})));renderProgressiveList('#time-feature-affinity',reliable,x=>`<div class="affinity-row"><strong>${esc(x.timeBand)} × ${esc(x.featureLabel)}</strong><span>相性 ${x.affinityScore.toFixed(1)}</span><small>完走 ${percent(x.completionRate)} / Skip ${percent(x.skipRate)} / Early ${percent(x.earlySkipRate)}・${x.detailEventCount}件</small></div>`,'十分なサンプルがありません');renderProgressiveList('#entity-changes',entities,x=>`<div class="insight-text"><strong>${esc(x.label)}</strong><small>${esc(({artists:'Artist',albums:'Album',genres:'Genre'})[x.kind])} · ${esc(x.signals.join(' / '))} · ${x.baselinePlayCount}→${x.recentPlayCount}回</small></div>`,'目立つ変化はありません');renderProgressiveList('#listening-profile',d.listeningProfile,x=>`<div class="profile-row ${x.score==null?'insufficient':''}"><strong>${esc(x.featureLabel)}</strong><span>${esc(x.level)}</span><small>${x.score==null?'—':`スコア ${x.score.toFixed(1)}・${x.detailEventCount}件`}</small></div>`)}
function recommendationList(selector,rows,reason){renderProgressiveList(selector,rows,x=>trackItem(x,reason(x)),'今の条件では候補がありません')}
function renderRecommendations(d){$('#auto-insight-cards').innerHTML=d.insightCards.length?d.insightCards.map(x=>`<article class="auto-insight"><strong>${esc(x.title)}</strong><p>${esc(x.message)}</p></article>`).join(''):empty('十分に強い変化はまだありません');recommendationList('#current-recommendations',d.recommendations,x=>`スコア ${x.score.toFixed(1)}・${x.reasons.join(' / ')}`);recommendationList('#rediscovery-recommendations',d.rediscoveryRecommendations,x=>x.reason);recommendationList('#low-play-discoveries',d.lowPlayDiscoveries,x=>x.reasons.join(' / '));wireTrackLinks()}
function wireTrackLinks(){$$('.insight-track').forEach(button=>button.onclick=()=>{$$('.nav-item,.page').forEach(x=>x.classList.remove('active'));$('.nav-item[data-page="tracks"]').classList.add('active');$('#tracks').classList.add('active');$('#track-title').value=button.dataset.trackTitle;state.tracksPage=1;loadTracks()})}
function syncRankingFilterUI(){const artist=$('#ranking-artist'),genre=$('#ranking-genre');artist.closest('.ranking-filter').classList.toggle('has-value',Boolean(artist.value));genre.closest('.ranking-filter').classList.toggle('has-value',Boolean(genre.value));$('#clear-ranking-filters').disabled=!artist.value&&!genre.value}
async function loadRankingFilters(){if(state.rankingFiltersLoaded){syncRankingFilterUI();return}const d=await api('/api/ranking-filters');$('#ranking-artist').innerHTML='<option value="">すべてのArtist</option>'+d.artists.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('#ranking-genre').innerHTML='<option value="">すべてのGenre</option>'+d.genres.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('#ranking-artist').value=state.rankingArtist;$('#ranking-genre').value=state.rankingGenre;state.rankingFiltersLoaded=true;syncRankingFilterUI()}
async function loadRankings(){await loadRankingFilters();const dimensions=['tracks','artists','albums','genres'],base=new URLSearchParams({period:state.rankingsPeriod,metric:state.rankingMetric});if(state.rankingArtist)base.set('artist',state.rankingArtist);if(state.rankingGenre)base.set('genre',state.rankingGenre);if(state.rankingsPeriod==='custom'){base.set('startDate',$('#rankings-start-date').value.trim());base.set('endDate',$('#rankings-end-date').value.trim())}const error=$('#rankings-period-error');error.textContent='';dimensions.forEach(dimension=>delete progressiveListLimits[`#ranking-${dimension}`]);let results;try{results=await Promise.all(dimensions.map(dimension=>{const params=new URLSearchParams(base);params.set('dimension',dimension);return api(`/api/rankings?${params}`)}))}catch(e){error.textContent=e.message;return}results.forEach((d,index)=>{const dimension=dimensions[index],max=Math.max(...d.items.map(x=>Number(x.value)||0),1);renderProgressiveList(`#ranking-${dimension}`,d.items,(x,i)=>`<div class="ranking-row"><span class="ranking-position">${i+1}</span><div class="ranking-name"><strong>${esc(x.label)}</strong>${x.subtitle?`<small>${esc(x.subtitle)}</small>`:''}<i style="--width:${Math.max(2,Number(x.value)/max*100)}%"></i></div><b>${state.rankingMetric==='duration'?playbackDuration(x.value):`${Number(x.value).toLocaleString()}回`}</b></div>`)});const note=$('#rankings-legacy-note');note.hidden=state.rankingMetric!=='duration';note.textContent=`※ 再生時間は ${results[0].legacyPlaybackCutoff} 以降の詳細イベントで集計します。`}
function renderPagination(selector,page,total,pageSize,load){const pages=Math.max(1,Math.ceil(total/pageSize)),root=$(selector);root.innerHTML=total>pageSize?`<button data-page="prev" ${page<=1?'disabled':''}>前へ</button><span>${page} / ${pages}ページ（${Number(total).toLocaleString()}件）</span><button data-page="next" ${page>=pages?'disabled':''}>次へ</button>`:'';root.querySelectorAll('button').forEach(button=>button.onclick=()=>load(button.dataset.page==='prev'?page-1:page+1))}
function renderRemoteSortHead(selector,columns,currentSort,currentOrder,onSort){$(selector).innerHTML=`<tr>${columns.map(column=>`<th><button type="button" class="sort-button ${column.sort===currentSort?'active':''}" data-remote-sort="${column.sort}" data-indicator="${column.sort===currentSort?(currentOrder==='asc'?'↑':'↓'):''}" aria-sort="${column.sort===currentSort?(currentOrder==='asc'?'ascending':'descending'):'none'}">${esc(column.label)}</button></th>`).join('')}</tr>`;$(selector).querySelectorAll('[data-remote-sort]').forEach(button=>button.onclick=()=>onSort(button.dataset.remoteSort,button.dataset.remoteSort===currentSort&&currentOrder==='asc'?'desc':'asc'))}
function preference(value){if(value==null)return '<span class="preference">未取込</span>';const cls=value>0?'good':value<0?'bad':'';return `<span class="preference ${cls}">${value>0?'+':''}${value}</span>`}
function preferenceEditor(x){if(x.playbackPreference==null)return preference(null);return `<select class="preference-editor" data-track-id="${esc(x.trackId)}" aria-label="${esc(x.title)}のGood / Bad">${Array.from({length:21},(_,i)=>i-10).map(v=>`<option value="${v}" ${v===x.playbackPreference?'selected':''}>${v>0?'+':''}${v}</option>`).join('')}</select>`}
function favoriteEditor(x){if(x.playbackPreference==null)return `<span class="favorite">${x.favorite===1?'♥':'—'}</span>`;return `<button class="favorite-editor ${x.favorite===1?'active':''}" data-track-id="${esc(x.trackId)}" data-favorite="${x.favorite===1}" aria-label="${esc(x.title)}のお気に入り">${x.favorite===1?'♥':'♡'}</button>`}
async function loadTracks(){
  const params=new URLSearchParams({period:state.tracksPeriod,sort:state.tracksSort,order:state.tracksOrder,page:state.tracksPage});
  [['title','#track-title'],['artist','#track-artist'],['album','#track-album'],['genre','#track-genre']].forEach(([key,selector])=>{const v=$(selector).value.trim();if(v)params.set(key,v)});
  if(state.tracksPeriod==='custom'){params.set('startDate',$('#track-start-date').value);params.set('endDate',$('#track-end-date').value)}
  const error=$('#period-error');error.textContent='';
  let d;try{d=await api(`/api/tracks?${params}`)}catch(e){error.textContent=e.message;$('#tracks-body').innerHTML=`<tr><td colspan="13">${empty('期間を確認してください')}</td></tr>`;return}
  $$('.sort-button').forEach(button=>{const active=button.dataset.sort===state.tracksSort;button.classList.toggle('active',active);button.setAttribute('aria-sort',active?(state.tracksOrder==='asc'?'ascending':'descending'):'none');button.dataset.indicator=active?(state.tracksOrder==='asc'?'↑':'↓'):''});
  $('#tracks-body').innerHTML=d.tracks.length?d.tracks.map(x=>`<tr>
    <td title="${esc(x.title)}"><strong>${esc(x.title)}</strong><small>${x.genre?esc(x.genre):'—'}${x.inLibrary?'':' · 履歴のみ'}</small></td><td title="${esc(x.artist)}">${esc(x.artist)||'—'}</td><td title="${esc(x.album)}">${esc(x.album)||'—'}</td>
    <td>${preferenceEditor(x)}</td><td>${favoriteEditor(x)}</td><td>${x.hasFingerprint?'✓':'—'}</td>
    <td>${x.playCount}回</td><td>${playbackDuration(x.totalPlayTime)}</td><td>${percent(x.completionRate)}</td><td>${percent(x.skipRate)}</td><td>${x.earlySkipCount}回</td><td>${percent(x.earlySkipRate)}</td>
    <td>${x.lastPlayedAt?new Date(x.lastPlayedAt).toLocaleString('ja-JP'):'—'}</td></tr>`).join(''):`<tr><td colspan="13">${empty()}</td></tr>`;
  $$('.preference-editor').forEach(el=>el.onchange=()=>savePreference(el.dataset.trackId,Number(el.value),favoriteValue(el.dataset.trackId)));
  $$('.favorite-editor').forEach(el=>el.onclick=()=>savePreference(el.dataset.trackId,preferenceValue(el.dataset.trackId),el.dataset.favorite!=='true'));
  renderPagination('#tracks-pagination',d.page,d.total,d.pageSize,page=>{state.tracksPage=page;loadTracks()});
}
function preferenceValue(trackId){return Number($(`.preference-editor[data-track-id="${CSS.escape(trackId)}"]`).value)}
function favoriteValue(trackId){return $(`.favorite-editor[data-track-id="${CSS.escape(trackId)}"]`).dataset.favorite==='true'}
async function savePreference(trackId,playbackPreference,favorite){try{await api(`/api/preferences/${encodeURIComponent(trackId)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({playbackPreference,favorite})});await Promise.all([loadTracks(),loadDashboard()])}catch(e){alert(`再生傾向を保存できませんでした: ${e.message}`);await loadTracks()}}
const value=(v,digits=2)=>v==null?'—':Number(v).toFixed(digits);
async function loadSources(){
  const d=await api(`/api/sources/${state.sourceKind}?page=${state.sourcesPage}&sort=${state.sourceSort}&order=${state.sourceOrder}`),trackKind=['track_features','volume_normalization'].includes(state.sourceKind);
  $('#source-summary').innerHTML=[['データ種別',kindLabel(state.sourceKind)],['登録項目',`${d.count}件`],...(d.derivedFrom?[['由来','Libraryから自動集計']]:[]),...(trackKind?[['Library紐付け',`${d.linkedCount} / ${d.count}曲`]]:[])].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  const configs={library_genres:[['ジャンル','title',x=>esc(x.title)],['曲数','trackCount',x=>`${x.trackCount}曲`],['Artist数','artistCount',x=>`${x.artistCount}`],['Library取込日時','importedAt',x=>x.importedAt?new Date(x.importedAt).toLocaleString('ja-JP'):'—']],track_features:[['曲','title',x=>`${esc(x.title)}<small>${esc(x.subtitle||'')}</small>`],['Library','linked',x=>x.linked?'✓':'未紐付け'],['Tempo','tempo',x=>value(x.data.features?.tempo,1)],['Energy','energy',x=>value(x.data.features?.energy)],['Vocal','vocal',x=>value(x.data.features?.vocal)],['解析Version','analysisVersion',x=>x.data.analysisVersion]],volume_normalization:[['曲','title',x=>`${esc(x.title)}<small>${esc(x.subtitle||'')}</small>`],['Library','linked',x=>x.linked?'✓':'未紐付け'],['Integrated LUFS','integratedLUFS',x=>value(x.data.integratedLUFS,1)],['True Peak','truePeakDBTP',x=>value(x.data.truePeakDBTP,1)],['補正Gain','normalizationGainDB',x=>value(x.data.normalizationGainDB,1)],['相対パス','relativePath',x=>esc(x.data.relativePath)]],playlists:[['プレイリスト','title',x=>esc(x.title)],['種類','kind',x=>esc(x.data.kind)],['タグ','tags',x=>esc((x.data.tags||[]).join(', ')||'—')],['収録曲','trackCount',x=>`${x.trackCount}曲`],['Library紐付け','linkedTrackCount',x=>`${x.linkedTrackCount} / ${x.trackCount}`],['更新日時','updatedAt',x=>x.data.updatedAt?new Date(x.data.updatedAt).toLocaleString('ja-JP'):'—']],equalizer:[['設定 / プリセット','title',x=>esc(x.title)],['区分','recordType',x=>esc(x.data.recordType)],['有効','enabled',x=>x.data.isEnabled==null?'—':(x.data.isEnabled?'ON':'OFF')],['Preamp','preamp',x=>value(x.data.preamp,1)],['Band Gain','gains',x=>esc((x.data.gains||x.data.bands?.map(b=>b.gain)||[]).join(', '))]],genre_presets:[['プリセット','title',x=>esc(x.title)],['有効ジャンル数','genreCount',x=>(x.data.enabledGenreNames||[]).length],['ジャンル','genres',x=>esc((x.data.enabledGenreNames||[]).join(', ')||'—')],['未分類設定','unassigned',x=>x.data.includesUnassignedGenreSetting==null?'既定':(x.data.includesUnassignedGenreSetting?'含む':'含まない')]]};
  const columns=configs[state.sourceKind];renderRemoteSortHead('#sources-head',columns.map(([label,sort])=>({label,sort})),state.sourceSort,state.sourceOrder,(sort,order)=>{state.sourceSort=sort;state.sourceOrder=order;state.sourcesPage=1;loadSources()});$('#sources-body').innerHTML=d.items.length?d.items.map(x=>`<tr>${columns.map(([, ,render])=>`<td>${render(x)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${columns.length}">${empty('このJSONはまだImportされていません')}</td></tr>`;
  renderPagination('#sources-pagination',d.page,d.count,d.pageSize,page=>{state.sourcesPage=page;loadSources()});
}
async function loadImports(){const d=await api('/api/imports');renderProgressiveTable('#imports-body','#imports-more',d.imports,x=>`<tr>${sortableCell(x.importedAt,`${new Date(x.importedAt).toLocaleString('ja-JP')}<small>${esc(x.sourceFilename)}</small>`)}${sortableCell(kindLabel(x.dataKind),esc(kindLabel(x.dataKind)))}${sortableCell(x.newCount,x.newCount)}${sortableCell(x.updatedCount,x.updatedCount)}${sortableCell(x.duplicateCount,x.duplicateCount)}${sortableCell(x.errorCount,x.errorCount)}</tr>`,6,'Import履歴はまだありません')}
async function upload(file){if(!file)return;const zone=$('#drop-zone'),result=$('#import-result');zone.querySelector('strong').textContent='Import中…';try{const form=new FormData();form.append('file',file);const d=await api('/api/import',{method:'POST',body:form});result.innerHTML=`<p class="subtitle">${esc(kindLabel(d.dataKind))}としてImportしました。</p><div class="result"><div><strong>${d.newCount}</strong><span>新規</span></div><div><strong>${d.updatedCount}</strong><span>更新</span></div><div><strong>${d.duplicateCount}</strong><span>重複</span></div><div><strong>${d.errorCount}</strong><span>エラー</span></div></div>${d.errors.length?`<p class="subtitle">${d.errors.map(esc).join('<br>')}</p>`:''}`;await Promise.all([loadImports(),loadDashboard()])}catch(e){result.innerHTML=`<p class="subtitle">Importできませんでした: ${esc(e.message)}</p>`}finally{zone.querySelector('strong').textContent='JSONをここへドロップ';$('#file-input').value=''}}
const pageNames=new Set($$('.page').map(page=>page.id)),insightTabNames=new Set($$('#insights-tabs button').map(button=>button.dataset.insightTab));
function showInsightsTab(tab){state.insightsTab=insightTabNames.has(tab)?tab:'recommendations';$$('#insights-tabs button').forEach(button=>{const active=button.dataset.insightTab===state.insightsTab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});$$('[data-insight-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.insightPanel===state.insightsTab))}
function showBehaviorTab(tab){const selected=$$('[data-behavior-tab]').some(button=>button.dataset.behaviorTab===tab)?tab:'source';$$('[data-behavior-tab]').forEach(button=>{const active=button.dataset.behaviorTab===selected;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});$$('[data-behavior-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.behaviorPanel===selected))}
function routeHash(page,tab){return `#${page}${page==='insights'?`/${tab||state.insightsTab}`:''}`}
function showPage(page,tab,{load=true}={}){const selected=pageNames.has(page)?page:'dashboard';$$('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.page===selected));$$('.page').forEach(section=>section.classList.toggle('active',section.id===selected));if(selected==='insights')showInsightsTab(tab);if(!load)return;if(selected==='dashboard')loadDashboard();if(selected==='history')loadMusicHistory();if(selected==='insights')loadInsights();if(selected==='rankings')loadRankings();if(selected==='tracks')loadTracks();if(selected==='sources')loadSources();if(selected==='import')loadImports()}
function currentRoute(){const [page,tab]=location.hash.slice(1).split('/');return {page:pageNames.has(page)?page:'dashboard',tab:insightTabNames.has(tab)?tab:'recommendations'}}
function navigate(page,tab){const hash=routeHash(page,tab);if(location.hash===hash){showPage(page,tab);return}history.pushState(null,'',hash);showPage(page,tab)}
$$('.nav-item').forEach(button=>button.onclick=()=>navigate(button.dataset.page));
$$('#insights-tabs button').forEach(button=>button.onclick=()=>navigate('insights',button.dataset.insightTab));
$$('[data-behavior-tab]').forEach(button=>button.onclick=()=>showBehaviorTab(button.dataset.behaviorTab));
window.addEventListener('hashchange',()=>{const route=currentRoute();showPage(route.page,route.tab)});
$$('#source-tabs button').forEach(b=>b.onclick=()=>{$$('#source-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sourceKind=b.dataset.kind;state.sourcesPage=1;state.sourceSort='title';state.sourceOrder='asc';loadSources()});
$$('.periods button').forEach(b=>b.onclick=()=>{const group=b.closest('.periods');group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(group.dataset.target==='dashboard'){state.dashboardPeriod=b.dataset.period;$('#dashboard-custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('dashboard');Object.keys(progressiveListLimits).forEach(key=>delete progressiveListLimits[key]);loadDashboard()}else if(group.dataset.target==='insights'){state.insightsPeriod=b.dataset.period;$('#insights-custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('insights');loadInsights()}else if(group.dataset.target==='rankings'){state.rankingsPeriod=b.dataset.period;$('#rankings-custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('rankings');loadRankings()}else{state.tracksPeriod=b.dataset.period;state.tracksPage=1;$('#custom-period').hidden=b.dataset.period!=='custom';if(b.dataset.period==='custom')initializeCustomPeriod('track');loadTracks()}});
$$('#ranking-metrics button').forEach(b=>b.onclick=()=>{$$('#ranking-metrics button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.rankingMetric=b.dataset.metric;loadRankings()});
$('#ranking-artist').onchange=e=>{state.rankingArtist=e.target.value;syncRankingFilterUI();loadRankings()};
$('#ranking-genre').onchange=e=>{state.rankingGenre=e.target.value;syncRankingFilterUI();loadRankings()};
$('#clear-ranking-filters').onclick=()=>{state.rankingArtist='';state.rankingGenre='';$('#ranking-artist').value='';$('#ranking-genre').value='';syncRankingFilterUI();loadRankings()};
$$('#insights-quality button').forEach(b=>b.onclick=()=>{$$('#insights-quality button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.insightsQuality=b.dataset.quality;loadInsights()});
$$('#insight-features button').forEach(b=>b.onclick=()=>{$$('#insight-features button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.insightFeature=b.dataset.feature;loadFeatureInsights().catch(e=>{$('#insights-period-error').textContent=e.message})});
$$('#rankings-custom-period input').forEach(input=>input.onchange=loadRankings);
let searchTimer;$$('.track-filters input').forEach(input=>input.oninput=()=>{clearTimeout(searchTimer);state.tracksPage=1;searchTimer=setTimeout(loadTracks,250)});
$$('#custom-period input').forEach(input=>input.onchange=()=>{state.tracksPage=1;loadTracks()});
$$('#dashboard-custom-period input').forEach(input=>input.onchange=loadDashboard);
$$('#insights-custom-period input').forEach(input=>input.onchange=loadInsights);
$('#clear-track-filters').onclick=()=>{$$('.track-filters input').forEach(input=>input.value='');state.tracksPage=1;loadTracks()};
$$('.sort-button').forEach(button=>button.onclick=()=>{if(state.tracksSort===button.dataset.sort)state.tracksOrder=state.tracksOrder==='asc'?'desc':'asc';else{state.tracksSort=button.dataset.sort;state.tracksOrder='asc'}state.tracksPage=1;loadTracks()});
$('#file-input').onchange=e=>upload(e.target.files[0]);const zone=$('#drop-zone');['dragenter','dragover'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.remove('drag')}));zone.addEventListener('drop',e=>upload(e.dataTransfer.files[0]));
initializeSortableTables();const initialRoute=currentRoute();if(!location.hash)history.replaceState(null,'',routeHash(initialRoute.page,initialRoute.tab));showPage(initialRoute.page,initialRoute.tab);
